unicode_mapping:
  你: U+4F60
  好: U+597D
  世: U+4E16
  界: U+754C
  中国: U+4E2D U+56FD
  字: U+5B57
  汉: U+6C49
  家: U+5BB6
  语: U+8BED
  言: U+8A00
  早: U+65E9
  上: U+4E0A
  学: U+5B66
  习: U+4E60
  书: U+4E66
  新: U+65B0
  报: U+62A5
  社: U+793E
  电: U+7535
  视: U+89C6
  频: U+9891
  朋: U+670B
  友: U+53CB
  车: U+8F66
  音: U+97F3
  乐: U+4E50
