unicode_mapping:
  à: U+00E0
  â: U+00E2
  æ: U+00E6
  ç: U+00E7
  è: U+00E8
  é: U+00E9
  ê: U+00EA
  ë: U+00EB
  î: U+00EE
  ï: U+00EF
  ô: U+00F4
  œ: U+0153
  ù: U+00F9
  û: U+00FB
  ü: U+00FC
  ÿ: U+00FF
  À: U+00C0
  Â: U+00C2
  Ç: U+00C7
  È: U+00C8
  É: U+00C9
  Ê: U+00CA
  Ë: U+00CB
  Î: U+00CE
  Ï: U+00CF
  Ô: U+00D4
  Œ: U+0152
  Ù: U+00D9
  Û: U+00DB
  Ü: U+00DC
  Ÿ: U+0178
